# Generated by Django 2.1.5 on 2019-08-12 05:32

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='category_img/', verbose_name='Изображение категории')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.CharField(max_length=255, null=True, verbose_name='Описание страницы')),
                ('page_keywords', models.TextField(null=True, verbose_name='Keywords')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание категории')),
                ('views', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать категорию ?')),
                ('for_fiz', models.BooleanField(default=True, verbose_name='Для физ лиц')),
                ('for_ur', models.BooleanField(default=False, verbose_name='Для юр лиц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название фильтра')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название товара')),
                ('name_lower', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.IntegerField(db_index=True, default=0, verbose_name='Цена за литр')),
                ('discount', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Скидка %')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.TextField(null=True, verbose_name='Описание страницы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание товара')),
                ('length', models.CharField(default='не указано', max_length=15, verbose_name='Длина')),
                ('width', models.CharField(default='не указано', max_length=15, verbose_name='Ширина')),
                ('volume', models.CharField(default='1', max_length=100, verbose_name='Доступные объемы(например 0,5;1;3)')),
                ('height', models.CharField(default='не указано', max_length=15, verbose_name='Высота')),
                ('goog_time', models.CharField(default='1 год', max_length=15, verbose_name='Срок годности')),
                ('article', models.CharField(max_length=50, null=True, verbose_name='Артикул')),
                ('weight', models.CharField(default='не указано', max_length=15, verbose_name='Вес')),
                ('ph', models.CharField(default='0', max_length=15, verbose_name='pH')),
                ('fasovka', models.CharField(blank=True, default='не указано', max_length=50, null=True, verbose_name='Фасовка')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать товар ?')),
                ('is_present', models.BooleanField(db_index=True, default=True, verbose_name='Товар в наличии ?')),
                ('buys', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Filter', verbose_name='Фильтр')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/%d/%s', verbose_name='Изображение товара')),
                ('image_small', models.CharField(blank=True, default='', max_length=255)),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная картинка ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение для товара',
                'verbose_name_plural': 'Изображения для товара',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Промокод (для создания рандомного значения оставить пустым)')),
                ('promo_discount', models.IntegerField(default=0, verbose_name='Скидка на заказ')),
                ('use_counts', models.IntegerField(blank=True, default=1, verbose_name='Кол-во использований')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Неограниченное кол-во использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('expiry', models.DateTimeField(default=datetime.datetime(2019, 8, 12, 5, 32, 41, 567960, tzinfo=utc), verbose_name='Срок действия безлимитного кода')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название подкатегории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='sub_category_img/', verbose_name='Изображение подкатегории')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.CharField(max_length=255, null=True, verbose_name='Описание страницы')),
                ('page_keywords', models.TextField(null=True, verbose_name='Keywords')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание подкатегории')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка на все товары в подкатегории %')),
                ('views', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать подкатегорию ?')),
                ('for_fiz', models.BooleanField(default=True, verbose_name='Для физ лиц')),
                ('for_ur', models.BooleanField(default=False, verbose_name='Для юр лиц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(blank=True, db_index=True, to='item.SubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='filter',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.SubCategory', verbose_name='Подкатегория'),
        ),
    ]
