# Generated by Django 2.1.5 on 2019-08-12 06:37

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название подкатегории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='sub_category_img/', verbose_name='Изображение подкатегории')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.CharField(max_length=255, null=True, verbose_name='Описание страницы')),
                ('page_keywords', models.TextField(null=True, verbose_name='Keywords')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание подкатегории')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка на все товары в подкатегории %')),
                ('views', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать подкатегорию ?')),
                ('for_fiz', models.BooleanField(default=True, verbose_name='Для физ лиц')),
                ('for_ur', models.BooleanField(default=False, verbose_name='Для юр лиц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Основная подкатегория', 'verbose_name_plural': 'Основные подкатегории'},
        ),
        migrations.AlterField(
            model_name='filter',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.SubSubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(blank=True, db_index=True, to='item.SubSubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 6, 37, 13, 998951, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='sub_category_img/', verbose_name='Изображение подкатегории'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.SubCategory', verbose_name='Основная подкатегория'),
        ),
    ]
