# Generated by Django 2.1.5 on 2019-08-13 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190812_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 10, 28, 29, 540660, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
