# Generated by Django 2.1.5 on 2019-09-18 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190918_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='unit',
            field=models.CharField(choices=[('л.', 'Литры'), ('шт.', 'Штуки')], default='л.', max_length=5, verbose_name='Еденица измерения'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 18, 19, 45, 22, 279217, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
