# Generated by Django 2.1.5 on 2019-08-13 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190813_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 12, 48, 57, 42646, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
