# Generated by Django 2.1.5 on 2019-08-13 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190813_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена за литр'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 12, 58, 10, 820561, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
