# Generated by Django 2.1.5 on 2019-08-13 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20190813_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 18, 25, 58, 551364, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
