# Generated by Django 2.1.5 on 2019-08-15 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20190813_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Основная категория', 'verbose_name_plural': 'Основные категории'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='goog_time',
            new_name='good_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='for_fiz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='for_ur',
        ),
        migrations.RemoveField(
            model_name='item',
            name='article',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='for_fiz',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='for_ur',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='for_fiz',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='for_ur',
        ),
        migrations.AddField(
            model_name='item',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='item',
            name='zapah',
            field=models.CharField(blank=True, default='не указано', max_length=50, null=True, verbose_name='Запах'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6, verbose_name='Цена за литр'),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание товара (если оставить пустым, то будет взято 30 первыз слов из описания товара)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 11, 53, 50, 801724, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
