# Generated by Django 2.1.5 on 2019-08-15 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20190815_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фильтр'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buys',
            field=models.IntegerField(default=0, verbose_name='Покупок'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара (отображается на странице товара)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ph',
            field=models.CharField(blank=True, default='0', max_length=15, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание товара (отображается в карточке товара) (если оставить пустым, то будет взято 15 первых слов из описания товара)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 17, 45, 23, 368631, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
