# Generated by Django 2.1.5 on 2019-08-15 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20190815_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 20, 5, 32, 776664, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
