# Generated by Django 2.1.5 on 2019-08-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена за ед.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Общая стоимость'),
        ),
    ]
