# Generated by Django 2.1.5 on 2019-08-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20190815_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Объем'),
        ),
    ]
