# Generated by Django 2.1.5 on 2019-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bonuses',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Бонус с заказа'),
        ),
    ]
