# Generated by Django 2.1.5 on 2019-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190813_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена за ед.'),
        ),
    ]
