# Generated by Django 2.1.5 on 2019-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190813_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед.'),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
